name: Update package lists

on:
  workflow_dispatch:
  schedule:
    - cron: '28 1/2 * * *'

concurrency:
  group: ${{ github.workflow }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          ref: ${{ github.head_ref }}

      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Generate the package lists
        run: |
          nix flake update gnu-elpa nongnu
          nix build .#package-lists -L
          cp -v result/*.* lists/

      - name: Revert flake.lock if no change has been made in lists/
        run: |
          if git diff --exit-code lists
          then
            git checkout HEAD -- flake.lock
          fi

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7
        with:
          commit_message: 'chore: Update the package lists'
